Don't build ov772x on Kernels below 4.18
This driver requires devm_regmap_init_sccb, with was added
for 4.18.

/devel/v4l/media_build/v4l/ov772x.c: In function 'ov772x_probe':
/devel/v4l/media_build/v4l/ov772x.c:1372:17: error: implicit declaration of function 'devm_regmap_init_sccb'; did you mean 'devm_regmap_init_ac97'? [-Werror=implicit-function-declaration]
  priv->regmap = devm_regmap_init_sccb(client, &ov772x_regmap_config);
                 ^~~~~~~~~~~~~~~~~~~~~
                 devm_regmap_init_ac97
/devel/v4l/media_build/v4l/ov772x.c:1372:15: warning: assignment to 'struct regmap *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  priv->regmap = devm_regmap_init_sccb(client, &ov772x_regmap_config);
               ^
cc1: some warnings being treated as errors

Signed-off-by: Mauro Carvalho Chehab <mchehab+samsung@kernel.org>